### ISSUE TITLE
Wrong Reference

### ISSUE THREAD

**Issue by cyh1998jhu** [albrateanu/LYT-Net#1]
The reference [10] in your paper is wrong !!!!!!!!!!!

It should be

Retinexformer: One-stage Retinex-based Transformer for Low-light Image Enhancement. In ICCV 2023. Yuanhao Cai, Hao Bian, Jing Lin, Haoqian Wang, Radu Timofte, and Yulun Zhang.

You wrongly cite another paper !!!!!!!!!!!!!!!!!

**Comment by albrateanu** [comment]
Thank you. Reference has been revised and submitted for update.
