### ISSUE TITLE
Do you consider migrating Python versions？

### ISSUE THREAD

**Issue by stuhao251** [albrateanu/LYT-Net#10]
Hello, I am curious if you will release a PyTorch version of the project. The current TF version is not suitable for operation and learning

**Comment by albrateanu** [comment]
Hi, thanks for writing.

We will provide a PyTorch version to facilitate better understanding. Due to other projects going on, we don't estimate a faster release than June-July.

**Comment by albrateanu** [comment]
Hello stuhao251, PyTorch version has been added, detailed environment and code setup guide coming in the following days.

**Comment by stuhao251** [comment]
Thank you for your contribution！
