### ISSUE TITLE
关于pytorch版本

### ISSUE THREAD

**Issue by GZY2000** [albrateanu/LYT-Net#11]
您好，我想请问一下关于pytorch版本何时更新呀？

**Comment by albrateanu** [comment]
Hi, we have started working on the PyTorch version and hoping that we'll be able to release it by mid-July.

**Comment by GZY2000** [comment]
> 嗨，我们已经开始开发 PyTorch 版本，希望能够在 7 月中旬发布它。

好的，谢谢您的回复

**Comment by stuhao251** [comment]
太棒了，我也在等这个Pytorch版本的

**Comment by zhaoyc823** [comment]
感谢您的努力，期待着您的pytorch版本。

**Comment by albrateanu** [comment]
Hello all, PyTorch version has been added, detailed environment and code setup guide coming in the following days.

**Comment by GZY2000** [comment]
> Hello all, PyTorch version has been added, detailed environment and code setup guide coming in the following days.

好的，非常感谢您！

**Comment by zhaoyc823** [comment]
> 大家好，添加了 PyTorch 版本，详细的环境和代码设置指南将在接下来的几天内推出。
非常感谢您！

**Comment by zhaoyc823** [comment]
> Hello all, PyTorch version has been added, detailed environment and code setup guide coming in the following days.

非常感谢您！
