### ISSUE TITLE
how can i download the pre-trained model i want to use this to export onnx-model 

### ISSUE THREAD

**Issue by WYQ-Github** [albrateanu/LYT-Net#15]

**Comment by albrateanu** [comment]
Hello. Are you refering to PyTorch pre-trained models?

**Comment by VAhafonov** [comment]
@albrateanu Could you please share link for PyTorch pre-trained models

**Comment by cjl506** [comment]
Could you please share link for PyTorch pre-trained models

**Comment by albrateanu** [comment]
Link to pytorch weights has been shared under the pytorch readme file.
