### ISSUE TITLE
The derivative for ‘histc’ is not implemented

### ISSUE THREAD

**Issue by liuxiaoya396** [albrateanu/LYT-Net#17]
I met the same problem in PyTorch implementation : the derivative for ‘histc’ is not implemented. Is there a way to easily implement a histogram function with derivates?

Thank you for your time!

**Comment by albrateanu** [comment]
Hi.

Please make sure you have the latest version of the code. I also had this at an early stage within the PyTorch version implementation.

However, I will still look over the issue in case it persists.

**Comment by liuxiaoya396** [comment]
Yes，it is the latest version of the PyTorch code.

**Comment by albrateanu** [comment]
Hello. Histogram loss has been updated to use gaussian kernels to smoothen the distribution over bins, and essentially implement soft-binning instead of hard binning - to remain differentiable. 

Thanks for your comment.
