### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by xuehaohewangyu** [albrateanu/LYT-Net#5]
运行python main.py --test --dataset LOLv1 --weights pretrained_weights/LOL_v1.h5 会出现无法查找预权重文件，但是我明明创建了retrained_weights，将权重文件放到里面，这个怎么处理了作者

**Comment by albrateanu** [comment]
感谢您注意到这个问题
它应该是 LOLv1.h5 而不是 LOL_v1.h5

所以这应该有效： python main.py --test --dataset LOLv1 --weights pretrained_weights/LOLv1.h5

README 已更新
