### ISSUE TITLE
train.py中的h5文件

### ISSUE THREAD

**Issue by xuehaohewangyu** [albrateanu/LYT-Net#7]
Hi author, how do I get the .h5 file from my own trained network, it only generates experiments, and this file is just the h5 generated by different epochs, there is no overall parameter file, how can I solve it?

**Comment by albrateanu** [comment]
Hello, thanks for writing.

To train LYT-Net using your custom parameters, you will have to modify ```scripts/train.py ```, ```model/losses.py``` and ```model/arch.py``` as per your requirements. 

We will provide a configuration where users can set their custom parameters with more ease, but until then, this is the only way to train on custom options.

**Comment by xuehaohewangyu** [comment]
Thank you very much for your answer, I see that you are providing the pre-training weights h5 file, which means that the last h5 of the experiments is the best parameter for the whole training process?
