### ISSUE TITLE
Error when run:  python main.py --test --dataset LOLv1 --weights pretrained_weights/LOLv1.h5

### ISSUE THREAD

**Issue by KhanhLinh-2904** [albrateanu/LYT-Net#9]
Dear author, When I tried to run test with dataset LOLv1 and use pretrained_weight LOLv1.h5. It alwyas raises error like this: raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 0 layers, found 11 saved layers.)
It means that there is a discrepancy between the architecture of the model you're trying to load the weights into and the architecture of the model that was used to save the weights. Please let me know how to fix this error. Thank you

**Comment by albrateanu** [comment]
Hello, thanks for your message.

Please make sure the conda environment is configured correctly, the repository is up-to-date, and that you are using the latest provided weights.
